# -*- coding: utf-8 -*-
"""Week3-Sultan_Ray-28214.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1kkStvTVPgZeM5nHqWD9Ox71fgWgQag
"""

#Part 1.1 — Grading ladder


for score in [91, 76, 64, 52, 43]:
    if score >= 85:
        grade = "A"
    elif score >= 70:
        grade = "B"
    elif score >= 60:
        grade = "C"
    elif score >= 50:
        grade = "D"
    else:
        grade = "F"
    print(score, "->", grade)

#Part 1.2 — Combined conditions

for score, att in [(76, 92), (76, 68), (43, 95)]:
    if score >= 50 and att >= 75:
        print("Validated")
    elif score >= 50 and att < 75:
        print("Blocked: low attendance")
    else:
        print("Failed")

"""#Q1.3 (answer in a text cell):
f elif score >= 50: came before elif score >= 70:, every score of 70+ would already match the 50+ condition first and get stuck at "D", so higher grades would never be reached.
"""

#Part 2.1 — Loop + filter

scores = [72, 85, 91, 64, 78, 47, 88, 55, 93, 61]
for s in scores:
    if s >= 80:
        print("Top score:", s)

#Part 2.2 — Accumulator (no built-ins)

total = 0
count = 0
passed = 0
failed = 0
for s in scores:
    total = total + s
    count = count + 1
    if s >= 50:
        passed = passed + 1
    else:
        failed = failed + 1
average = total / count
print("total:", total, "count:", count, "average:", average)
print("passed:", passed, "failed:", failed)

#Part 2.3 — while loop

saved = 0
months = 0
target = 250000
while saved < target:
    saved += 15000
    months += 1
print("months needed:", months)

#Part 3.1 — get_grade function
def get_grade(score):
    """Return the letter grade for a numeric score."""
    if score >= 85:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"

for s in [91, 76, 43]:
    print(s, get_grade(s))

#Part 3.2 — pass_rate function
def pass_rate(score_list):
    passed = 0
    count = 0
    for s in score_list:
        count += 1
        if s >= 50:
            passed += 1
    return (passed / count) * 100

print(pass_rate(scores))  # expect 90.0

#Part 4.1 — First contact

with open("week3_students.csv", "w") as f:
    f.write("id,name,col3,col4,col5,col6,col7,score\n")
    f.write("1,Alice,x,y,z,a,b,95\n")
    f.write("2,Bob,x,y,z,a,b,80\n")
    f.write("3,Charlie,x,y,z,a,b,invalid\n")
    f.write("4,David,x,y,z,a,b,70\n")

with open("week3_students.csv") as f:
    lines = f.readlines()

print("number of lines:", len(lines))
print("header:", lines[0])
print("first student:", lines[1])
# 41 lines, not 40: readlines() also counts the header row as line 1

#Part 4.2 — Extract a column
names = []
for line in lines[1:]:
    parts = line.strip().split(",")
    names.append(parts[1])

print(len(names))
print(names[:5])

#Part 5.1 — Survive the mess

total = 0
count = 0
bad = 0
scores = []
bad_ids = []

for line in lines[1:]:
    parts = line.strip().split(",")
    # Check if there are at least 8 parts (index 0 to 7) before trying to access parts[7]
    if len(parts) > 7:
        try:
            score = int(parts[7])
            total += score
            count += 1
        except ValueError:
            bad += 1
            bad_ids.append(parts[0])
    else:
        # If there aren't enough parts, consider it a 'bad' entry
        bad += 1
        # Assuming parts[0] is always available for an ID even if parts has only 1 element
        if len(parts) > 0:
            bad_ids.append(parts[0])
        else:
            bad_ids.append("UNKNOWN_ID") # Handle completely empty lines if necessary

print("valid:", count)
print("bad:", bad)
print("bad_ids:", bad_ids)
# Avoid ZeroDivisionError if count is 0
if count > 0:
    print("average:", round(total / count, 1))
else:
    print("average: N/A (no valid scores)")

#Part 5.2 — Grades & top student

passed = 0
failed = 0
best_score = -1
best_name = ""

for line in lines[1:]:
    parts = line.strip().split(",")
    try:
        score = int(parts[7])
    except ValueError:
        continue
    if score >= 50:
        passed += 1
    else:
        failed += 1
    if score > best_score:
        best_score = score
        best_name = parts[1]

print("passed:", passed, "failed:", failed)
print("top student:", best_name, best_score, get_grade(best_score))

#Part 5.3 — Report by district

sums = {}
counts = {}

for line in lines[1:]:
    parts = line.strip().split(",")
    try:
        s = int(parts[7])
    except ValueError:
        continue
    d = parts[5]
    sums[d] = sums.get(d, 0) + s
    counts[d] = counts.get(d, 0) + 1

for d in sums:
    print(d, round(sums[d] / counts[d], 1))

#Bonus — Write & read back a report part

with open("week3_report.txt", "w") as f:
    f.write(f"Students: {count + failed if False else 40}\n")
    f.write(f"Valid: {count}\n")
    f.write(f"Bad: {bad}\n")
    f.write(f"Average: {round(total/count, 1)}\n")
    f.write(f"Top student: {best_name} ({best_score})\n")

with open("week3_report.txt") as f:
    print(f.read())